In [15]:
import sys
import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

sys.path.append(os.path.abspath(os.path.join('..')))
from src.data_loader import load_stock_data
from src.visualizer import plot_daily_candlestick
from src.features import create_features
from src.risk_manager import evaluate_trade_risk
from src.label import create_labels

In [16]:
# Set tanggal dinamis (Contoh: Menarik data dari 6 bulan lalu hingga hari ini)
hari_ini = datetime.now().strftime('%Y-%m-%d')
enam_bulan_lalu = (datetime.now() - timedelta(days=180)).strftime('%Y-%m-%d')

# 1. Panggil data BUMI riil dari Bursa Efek Indonesia (.JK)
# Data ini mencerminkan kondisi pasar riil per Juni 2026
df_bumi = load_stock_data(ticker="BUMI.JK", start_date=enam_bulan_lalu, end_date=hari_ini)
# ------------------------------------------

Mengunduh data terbaru untuk BUMI.JK dari Yahoo Finance...
Berhasil memuat 112 baris data untuk BUMI.JK.
Info Data Cleaning: Menghapus 4 baris data (NaN atau Volume 0).
Berhasil memuat 108 baris data bersih untuk BUMI.JK.

In [17]:
print(df_bumi)

             Open   High    Low  Close        Volume
Date
2025-12-24  382.0  384.0  360.0  362.0  4.795205e+09
2025-12-29  362.0  376.0  354.0  366.0  5.492663e+09
2025-12-30  370.0  372.0  362.0  366.0  2.812870e+09
2026-01-02  372.0  424.0  370.0  420.0  1.177109e+10
2026-01-05  428.0  476.0  420.0  464.0  1.304842e+10
...           ...    ...    ...    ...           ...
2026-06-15  165.0  191.0  163.0  173.0  1.333560e+10
2026-06-17  175.0  178.0  165.0  168.0  4.078183e+09
2026-06-18  169.0  173.0  163.0  171.0  2.760389e+09
2026-06-19  172.0  177.0  167.0  168.0  2.642491e+09
2026-06-22  170.0    NaN    NaN    NaN           NaN

[109 rows x 5 columns]

In [18]:
# plot_daily_candlestick(df=df_bumi, ticker_name="BUMI")

In [19]:
# df_bumi = calculate_atr(df_bumi)
# latest_data = df_bumi.iloc[-1]
# current_close = float(latest_data['Close'])
# current_atr = float(latest_data['ATR'])

# resisten_terdekat = 186.0  

# trade_analysis = evaluate_trade_risk(
#     entry_price=current_close,
#     atr=current_atr,
#     resistance_level=resisten_terdekat,
#     min_rr_ratio=2.0
# )

# # Cetak Hasil Validasi Hitam-di-Atas-Putih
# print("=== LIVE SYSTEM RISK EVALUATION ===")
# print(f"Harga Masuk Terkini     : Rp{trade_analysis['entry_price']}")
# print(f"Nilai Volatilitas (ATR) : Rp{round(current_atr, 2)}")
# print(f"Garis Aman Cut Loss (SL): Rp{trade_analysis['suggested_stop_loss']} (Terproteksi dari noise)")
# print(f"Target Resisten (TP)    : Rp{trade_analysis['target_profit_resistance']}")
# print(f"Rasio R-to-R Aktual     : {trade_analysis['actual_rr_ratio']}x")
# print("-----------------------------------")

# if trade_analysis['execute_trade']:
#     print("KEPUTUSAN SISTEM: ISI ORDER BELI! Matematika risiko mendukung penuh.")
# else:
#     print("KEPUTUSAN SISTEM: BLOKIR TRANSAKSI! Jarak ke resisten terlalu sempit, batalkan emosi Anda.")

## ADD LABELS & FEATURES

In [20]:
HORIZON = 5

df_bumi = load_stock_data(ticker="BUMI.JK", start_date=enam_bulan_lalu, end_date=hari_ini)
df_bumi = create_labels(df_bumi, HORIZON)
df_bumi = create_features(df_bumi)
df_bumi

Mengunduh data terbaru untuk BUMI.JK dari Yahoo Finance...
Berhasil memuat 112 baris data untuk BUMI.JK.
Info Data Cleaning: Menghapus 4 baris data (NaN atau Volume 0).
Berhasil memuat 108 baris data bersih untuk BUMI.JK.

,Open,High,Low,Close,Volume,trend_slope,return,risk,days_to_max,days_to_min,...,Volume_Ratio,Log_Return,Support_Zone_Low,Support_Zone_High,Resistance_Zone_Low,Resistance_Zone_High,Support,Resistance,distance_to_support,distance_to_resistance
Date,,,,,,,,,,,,,,,,,,,,,
2025-12-24,382.0,384.0,360.0,362.0,4.795205e+09,0.067539,0.246073,-0.073298,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2025-12-29,362.0,376.0,354.0,366.0,5.492663e+09,0.081215,0.337017,-0.022099,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2025-12-30,370.0,372.0,362.0,366.0,2.812870e+09,0.058378,0.308108,-0.021622,4.0,1.0,...,NaN,0.010989,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-02,372.0,424.0,370.0,420.0,1.177109e+10,0.018280,0.301075,-0.005376,3.0,1.0,...,NaN,0.000000,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-05,428.0,476.0,420.0,464.0,1.304842e+10,-0.001869,0.130841,-0.018692,2.0,1.0,...,NaN,0.137621,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-15,165.0,191.0,163.0,173.0,1.333560e+10,NaN,NaN,NaN,NaN,NaN,...,1.359440,0.114603,126.0,134.079011,215.920989,224.0,126.0,224.0,23.061767,30.861206
2026-06-17,175.0,178.0,165.0,168.0,4.078183e+09,NaN,NaN,NaN,NaN,NaN,...,2.494476,0.097046,126.0,135.268476,210.731524,220.0,126.0,220.0,29.372346,20.418014
2026-06-18,169.0,173.0,163.0,171.0,2.760389e+09,NaN,NaN,NaN,NaN,NaN,...,0.745104,-0.029328,126.0,134.899346,211.100654,220.0,126.0,220.0,25.278591,24.911630
2026-06-19,172.0,177.0,167.0,168.0,2.642491e+09,NaN,NaN,NaN,NaN,NaN,...,0.501607,0.017700,126.0,134.379433,205.620567,214.0,126.0,214.0,27.995778,19.546841
2026-06-22,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.481534,-0.017700,126.0,133.928842,204.071158,212.0,126.0,212.0,26.933077,20.041858

In [21]:
df_bumi.head(10)

,Open,High,Low,Close,Volume,trend_slope,return,risk,days_to_max,days_to_min,...,Volume_Ratio,Log_Return,Support_Zone_Low,Support_Zone_High,Resistance_Zone_Low,Resistance_Zone_High,Support,Resistance,distance_to_support,distance_to_resistance
Date,,,,,,,,,,,,,,,,,,,,,
2025-12-24,382.0,384.0,360.0,362.0,4.795205e+09,0.067539,0.246073,-0.073298,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2025-12-29,362.0,376.0,354.0,366.0,5.492663e+09,0.081215,0.337017,-0.022099,5.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2025-12-30,370.0,372.0,362.0,366.0,2.812870e+09,0.058378,0.308108,-0.021622,4.0,1.0,...,NaN,0.010989,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-02,372.0,424.0,370.0,420.0,1.177109e+10,0.018280,0.301075,-0.005376,3.0,1.0,...,NaN,0.000000,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-05,428.0,476.0,420.0,464.0,1.304842e+10,-0.001869,0.130841,-0.018692,2.0,1.0,...,NaN,0.137621,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-06,466.0,484.0,452.0,464.0,8.648117e+09,-0.009871,0.038627,-0.154506,1.0,5.0,...,NaN,0.099630,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-07,464.0,478.0,452.0,452.0,6.102514e+09,-0.025000,0.034483,-0.150862,3.0,4.0,...,NaN,0.000000,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-08,450.0,460.0,442.0,460.0,3.629921e+09,-0.029333,0.066667,-0.124444,2.0,3.0,...,NaN,-0.026202,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-09,470.0,480.0,456.0,462.0,7.430491e+09,-0.025106,0.021277,-0.161702,1.0,2.0,...,NaN,0.017544,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836
2026-01-12,468.0,472.0,394.0,436.0,9.759300e+09,-0.009402,0.008547,-0.166667,1.0,5.0,...,NaN,0.004338,NaN,NaN,NaN,NaN,328.0,484.0,-14.594618,59.101836

In [22]:
df_bumi.tail(10)

,Open,High,Low,Close,Volume,trend_slope,return,risk,days_to_max,days_to_min,...,Volume_Ratio,Log_Return,Support_Zone_Low,Support_Zone_High,Resistance_Zone_Low,Resistance_Zone_High,Support,Resistance,distance_to_support,distance_to_resistance
Date,,,,,,,,,,,,,,,,,,,,,
2026-06-08,132.0,139.0,126.0,130.0,4.621182e+09,0.036364,0.227273,-0.045455,5.0,1.0,...,0.749406,-0.076161,137.0,145.001257,241.998743,250.0,137.0,250.0,-8.966306,83.332381
2026-06-09,130.0,148.0,129.0,146.0,5.625440e+09,0.051538,0.469231,-0.007692,5.0,1.0,...,1.111615,-0.066939,126.0,133.801089,230.198911,238.0,126.0,137.0,-2.840851,77.076085
2026-06-10,146.0,157.0,142.0,144.0,7.438604e+09,0.055479,0.308219,-0.068493,4.0,2.0,...,1.292543,0.116072,126.0,134.027611,229.972389,238.0,126.0,238.0,8.932778,57.515335
2026-06-11,144.0,147.0,136.0,140.0,2.994048e+09,0.050694,0.326389,-0.055556,3.0,1.0,...,1.601539,-0.013793,126.0,133.957263,230.042737,238.0,126.0,238.0,7.496971,59.751901
2026-06-12,144.0,162.0,143.0,157.0,6.630660e+09,0.013889,0.326389,-0.006944,2.0,1.0,...,0.638560,-0.028171,126.0,133.629628,224.370372,232.0,126.0,232.0,7.760534,55.812759
2026-06-15,165.0,191.0,163.0,173.0,1.333560e+10,NaN,NaN,NaN,NaN,NaN,...,1.359440,0.114603,126.0,134.079011,215.920989,224.0,126.0,224.0,23.061767,30.861206
2026-06-17,175.0,178.0,165.0,168.0,4.078183e+09,NaN,NaN,NaN,NaN,NaN,...,2.494476,0.097046,126.0,135.268476,210.731524,220.0,126.0,220.0,29.372346,20.418014
2026-06-18,169.0,173.0,163.0,171.0,2.760389e+09,NaN,NaN,NaN,NaN,NaN,...,0.745104,-0.029328,126.0,134.899346,211.100654,220.0,126.0,220.0,25.278591,24.911630
2026-06-19,172.0,177.0,167.0,168.0,2.642491e+09,NaN,NaN,NaN,NaN,NaN,...,0.501607,0.017700,126.0,134.379433,205.620567,214.0,126.0,214.0,27.995778,19.546841
2026-06-22,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.481534,-0.017700,126.0,133.928842,204.071158,212.0,126.0,212.0,26.933077,20.041858

In [23]:
feature_cols = ['ATR', 'RSI', 'Volume_Ratio', 'Log_Return', 'distance_to_support', 'distance_to_resistance']
label_cols = ['trend_slope', 'return', 'risk', 'days_to_max', 'days_to_min']

# Satukan ke dalam satu dataset besar
X_raw = df_bumi[feature_cols]
y_raw = df_bumi[label_cols]

print(f"✔ Matriks Fitur Mentah (X_raw) siap! dengan {X_raw.shape} kolom.")
print(f"✔ Matriks Target Mentah (y_raw) siap! dengan {y_raw.shape} kolom.")

✔ Matriks Fitur Mentah (X_raw) siap! dengan (109, 6) kolom.
✔ Matriks Target Mentah (y_raw) siap! dengan (109, 5) kolom.